name: vocab_master
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  isar: ^3.1.0+1
  isar_generator: ^3.1.0+1
  path_provider: ^2.1.5
  flutter_bloc: ^9.1.0
  google_fonts: ^6.2.1
  home_widget: ^0.7.0+1
  firebase_core: ^2.27.1
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  dio: ^5.8.0+1
  provider: ^6.1.4
  flutter_tts: ^3.8.5
  internet_connection_checker: ^1.0.0+1
  flutter_translate: ^4.1.0
  flutter_localizations:
    sdk: flutter
  in_app_update: ^4.2.3
  collapsible: ^1.0.0
  hive_generator: ^2.0.1
  hive: ^2.2.3
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6

flutter_native_splash:
  color: "#44B275"
  image: assets/images/logo.jpg


  android_12:
    image: assets/images/logo.jpg
    icon_background_color: "#44B275"

  web: false

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/logo.jpg

flutter:
  uses-material-design: true
  assets:
    - assets/images/
